### ISSUE TITLE
Where does the RefSeqVirusProtein come from?

### ISSUE THREAD

**Issue by lexikazen** [viralInformatics/VIGA#1]
I'm on the makedb step of the installation process, and I'm confused about where the RefSeqVirusProtein comes from. I don't see any steps saying to download a protein database but I'm assuming it's separate from nr since that's a separate database?

**Comment by viralInformatics** [comment]
Sorry for your confusion, the reference protein database is available for download at NCBI RefSeq via ftp as follows: wget -c ftp.ncbi.nlm.nih.gov/refseq/release/viral/viral.1.protein.faa.gz

**Comment by lexikazen** [comment]
Ok thank you so much!
