### ISSUE TITLE
A easy way to install VIGA

### ISSUE THREAD

**Issue by shufangwu** [viralInformatics/VIGA#2]
It is very hard to install VIGA. In particular,  the requirements.txt could not work on other platforms because this file contains "@file" instead of the version number. Is there any other way to use VIGA for users?

**Comment by viralInformatics** [comment]
Hello, sorry for the confusion, a requirements.txt file was created as we exported all the required python packages directly from the environment. Perhaps you can install the dependent python packages directly with the following command: **pip install pandas=1.1.5 numpy=1.19.5 matplotlib=3.3.4 biopython=1.79**, we have also updated the installation steps on github. Hope this helps!
