### ISSUE TITLE
update virus sequences

### ISSUE THREAD

**Issue by nyzhoulang** [viralInformatics/VIGA#4]
Hi,

I want to update these sequences in the local database instead of manually adding them to `SampleID.fa` every time.
How can I update the local virus sequences? 
> ########################################################################
> 
> The identified virus id is as follows:
>  ['1758150', '2070185', '2202644', '2219103', '2772518', '2823594', '2823610', '2825026', '2825049', '2825107', '2825292', '2825315', '2825322', '2825387', '2825535', '2825556', '2825683', '2825799', '2826244', '2826246', '2826255', '2826395', '2826461', '2826478', '2826517', '2826664', '2826700', '2826751', '2826764', '2826777', '2827634', '2827640', '2827671', '2827692', '2827769', '2827778', '2827841', '2827971', '2828112', '2828162', '2828213', '2831613', '38018', '743964']
> numbers of virus species:  44
> 
> ########################################################################
> 1758150, 2070185, 2202644, 2219103, 2772518, 2823594, 2823610, 2825026, 2825049, 2825107, 2825292, 2825315, 2825322, 2825387, 2825535, 2825556, 2825683, 2825799, 2826244, 2826246, 2826255, 2826395, 2826461, 2826478, 2826517, 2826664, 2826700, 2826751, 2826764, 2826777, 2827634, 2827640, 2827671, 2827692, 2827769, 2827778, 2827841, 2827971, 2828112, 2828162, 2828213, 2831613, 38018, 743964 is not in our database, please download the sequence from NCBI and put it in the ./genome/virus/ directory and named as SRR11941305.fa

Thanks,
Lang

**Comment by viralInformatics** [comment]
If you want to create a database yourself, you can modify the . /db/ under the sequence file final_out.fa.gz and the contents of the taxid_ref_3 file, which correspond to each other. the first column in the taxid_ref_3 file is the taxid of the virus, the second column is the Accession ID of the virus's GenBank or Refseq, and in final_out.fa.gz is the Accession ID and its corresponding fasta sequence. It is recommended to manually download the desired fasta sequence from the Nucleotide database with the virus ID identified in the first step and put it in SRR11941305.fa.
