### ISSUE TITLE
problems about downloading "prot.accession2taxid" file from https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/

### ISSUE THREAD

**Issue by aslangabriel99** [viralInformatics/VIGA#5]
Hi, I checked the FTP site and found there are a lot of files with the names containing prot.accession2taxid, would you like to tell me which file should I download, and where should I put it on my disk?
thanks a lot

**Comment by viralInformatics** [comment]
The FTP link is as follows: https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/prot.accession2taxid.gz
