### ISSUE TITLE
Syntax error when trying to run VIGA

### ISSUE THREAD

**Issue by lexikazen** [viralInformatics/VIGA#6]
Hi, I keep trying to run VIGA, and I end up getting a syntax error. I'm not sure if it's something I'm doing wrong or if I downloaded some of the software wrong but this is my input:
`(VIGA) al59331@MCW-19487 db % python /Volumes/annoying_af/VIGA/bin/0_run1_paired.py -h`

And this is the error:
 ```
 File "/Volumes/annoying_af/VIGA/bin/0_run1_paired.py", line 54
    if not os.path.exists(softdir+''/../db/final_out.fa'):
                                     ^
SyntaxError: invalid syntax
```
Any suggestions on how I can fix this?

**Comment by viralInformatics** [comment]
Hi, we have upgraded the file, you can re-download 0_run1_paired.py (https://github.com/viralInformatics/VIGA/blob/master/bin/0_run1_paired.py), feel free to contact us if you have any questions!

**Comment by lexikazen** [comment]
Perfect, thank you!
